name: FlameBank Web Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build FlameBank
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run build

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy FlameBank
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ secrets.SITE_URL }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Post-Deployment Ledger & Card Issuance
        run: |
          echo "Hashing user registrations on Web3..."
          node scripts/hash-registrations.js
          echo "Issuing embedded ledgers and virtual cards..."
          node scripts/issue-ledger-cards.js