name: FlameBank Web Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm test
        continue-on-error: false

  deploy:
    name: Deploy & Post-Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ secrets.SITE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }} # Optional: SSH deploy key for private repos
          publish_branch: gh-pages
          publish_dir: ./build

      - name: Wait for propagation (short)
        run: sleep 5

      - name: Hash registrations on Web3 (post-deploy)
        env:
          WEB3_RPC_URL: ${{ secrets.WEB3_RPC_URL }}
          WEB3_PRIVATE_KEY: ${{ secrets.WEB3_PRIVATE_KEY }}
        run: |
          node scripts/hash-registrations.js

      - name: Issue ledger records & cards (post-deploy)
        env:
          LEDGER_API_KEY: ${{ secrets.LEDGER_API_KEY }}
          CARD_ISSUER_KEY: ${{ secrets.CARD_ISSUER_KEY }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: |
          node scripts/issue-ledger-cards.js

      - name: Notify success
        run: echo "FlameBank deployed to ${{ secrets.SITE_URL }} and post-deploy tasks executed."- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v6
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./build